import Testing
import Foundation
@testable import AetherEngine

struct ProbeOpenDemuxerTests {
    /// Generated by Scripts/fetch-fixtures.sh (gitignored); the fixture
    /// test is skipped on machines that haven't run it.
    private static let fixtureURL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures/sdr-h264.mp4")

    private static var fixtureExists: Bool {
        FileManager.default.fileExists(atPath: fixtureURL.path)
    }

    @Test("probe(openDemuxer:) reports what probe(url:) reports, without consuming the demuxer",
          .enabled(if: fixtureExists))
    func matchesURLProbeAndLeavesDemuxerUsable() throws {
        let url = Self.fixtureURL
        let reference = try AetherEngine.probe(url: url)

        let demuxer = Demuxer()
        try demuxer.open(url: url)
        defer { demuxer.close() }
        let probe = AetherEngine.probe(openDemuxer: demuxer, url: url)

        #expect(probe.url == reference.url)
        #expect(probe.videoCodecName == reference.videoCodecName)
        #expect(probe.videoWidth == reference.videoWidth)
        #expect(probe.videoHeight == reference.videoHeight)
        #expect(probe.videoFormat == reference.videoFormat)
        #expect(probe.durationSeconds == reference.durationSeconds)
        #expect(probe.audioTracks.count == reference.audioTracks.count)
        #expect(probe.subtitleTracks.count == reference.subtitleTracks.count)
        #expect(probe.isLive == reference.isLive)

        // The whole point of this entry: the demuxer is handed to
        // load(preopenedDemuxer:) next, so the probe must leave it open
        // and intact.
        #expect(demuxer.videoStreamIndex >= 0)
        #expect(demuxer.duration > 0)
    }

    @Test("probe(openDemuxer:) on an unopened demuxer returns an empty probe, no crash")
    func unopenedDemuxerYieldsEmptyProbe() {
        let demuxer = Demuxer()
        let probe = AetherEngine.probe(
            openDemuxer: demuxer,
            url: URL(string: "https://example.com/x.mkv")!
        )
        #expect(probe.audioTracks.isEmpty)
        #expect(probe.videoCodecName == nil)
    }
}
