import Testing
import Foundation
@testable import AetherEngine

/// Exercises the patched matroska demuxer's `skip_attachments` option
/// (FFmpegBuild 0001-matroska-skip-attachments-option) through the
/// Demuxer's network/local routing. Fixture generated by
/// Scripts/fetch-fixtures.sh (gitignored); tests skip without it.
struct SkipAttachmentsTests {
    private static let fixtureURL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures/attachments.mkv")

    private static var fixtureExists: Bool {
        FileManager.default.fileExists(atPath: fixtureURL.path)
    }

    @Test("local opens read attachments: font infos present",
          .enabled(if: fixtureExists))
    func localOpenKeepsAttachments() throws {
        let demuxer = Demuxer()
        defer { demuxer.close() }
        try demuxer.open(url: Self.fixtureURL)
        #expect(demuxer.fontAttachmentInfos().count == 2)
    }

    @Test("skip_attachments removes attachment streams but the file still plays",
          .enabled(if: fixtureExists))
    func skipDropsAttachmentsAndKeepsVideo() throws {
        let demuxer = Demuxer()
        defer { demuxer.close() }
        demuxer.skipAttachmentsOverride = true
        try demuxer.open(url: Self.fixtureURL)

        // The whole Attachments element was skipped: no font infos, and
        // video remains demuxable (the skip didn't desync the parser).
        #expect(demuxer.fontAttachmentInfos().isEmpty)
        #expect(demuxer.videoStreamIndex >= 0)
        #expect(demuxer.duration > 0)
        let packet = try demuxer.readPacket()
        #expect(packet != nil)
    }
}
